import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '@/components/SideBar'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth/next'
import { Login } from '@/components/Login'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode,

}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>

        <SessionProvider session={session}>
          {!session ? (
            <Login/>
          ) : (

            <div className='flex h-screen overflow-hidden'>

              {/* <div className='min-w-[14rem] h-screen
                  overflow-y-auto '>
                
              </div> */}
              
              <SideBar />

              {/* ClientProvider - Notifications */}

              <div className='bg-[#343541] flex-1'>
                {children}
              </div>

            </div>

          )}

        </SessionProvider>
      </body>
    </html>
  )
}
